# -*- coding: utf-8 -*-
"""Test.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17hL60evQqA6cIqZGuxzFYd_9Y6zsRYm1
"""

print("Test code for API Wrapper")